version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 5
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      rehype:
        patterns:
          - "rehype-*"
      prettier:
        patterns:
          - "prettier"
          - "prettier-*"
          - "@prettier/*"
      git-hooks:
        patterns:
          - "husky"
          - "lint-staged"
