version: '3.6'
services:
  https-portal:
    image: steveltn/https-portal:1.12
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'bokken.io'
    restart: always
    depends_on:
      - bokken.io
    environment:
      DOMAINS: 'bokken.io -> http://bokken_io, www.bokken.io -> http://bokken_io, blog.bokken.io -> http://bokken_io, x.bokken.io -> http://bokken_io, app.bokken.io -> http://bokken_io:3000'
      STAGE: local
      ERROR_LOG: default
      ACCESS_LOG: default
    volumes:
      - type: bind
        source: /var/log/nginx
        target: ${PWD}/var/log/nginx

      
  bokken_io:
    image: nginx:alpine
    volumes:
      - type: bind
        source: /var/log/nginx
        target: ${PWD}/var/log/nginx
      - type: bind
        source: www.bokken.io/.
        target:  /usr/share/nginx/html/www.bokken.io/
      - type: bind
        source: blog.bokken.io/.
        target:  /usr/share/nginx/html/blog.bokken.io/
      - type: bind
        source: x.bokken.io/.
        target:  /usr/share/nginx/html/x.bokken.io/
      - type: bind
        source: assets/.
        target:  /usr/share/nginx/html/assets/
      - type: bind
        source: nginx/.
        target:  /etc/nginx

  app.bokken.io:
    image: app.bokken.io
    ports:
      - '3000:3000'
