version: '3.6'
services:
  https-portal:
    image: steveltn/https-portal:1.12
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'bokken.io'
    restart: always
    depends_on:
      - bokken.io
    environment:
      DOMAINS: 'bokken.io -> http://bokken.io:80, www.bokken.io -> http://bokken.io:80, blog.bokken.io -> http://bokken.io:80, career.bokken.io -> http://bokken.io:80, x.bokken.io -> http://bokken.io:80'
      STAGE: production

  bokken.io:
    image: bokken.io
