version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          command: |
            ssh bokken@bokken.io -o "StrictHostKeyChecking no" \
            "git clone https://github.com/negibokken/bokken.io.git; cd bokken.io; ./scripts/update; cd ..; rm -rf bokken.io"

workflows:
  version: 2
  deploy:
    jobs:
      - publish:
          filters:
            branches:
              only: master
