version: 2
jobs:
  publish:
    docker:
      - image: cimg/node:23.11.0
    steps:
      - checkout
      - run:
          command: ssh -p 2222 bokken@ssh.bokken.io -o "StrictHostKeyChecking no" "cd bokken.io && git pull -f && ./scripts/build && docker compose -f docker/docker-compose.yml up -d"

workflows:
  version: 2
  deploy:
    jobs:
      - publish:
          filters:
            branches:
              only: main
