version: 2
jobs:
  deploy-cloudflare:
    docker:
      - image: cimg/node:26.3.0
    steps:
      - checkout
      - run:
          name: Install pnpm and wrangler
          command: corepack enable && corepack prepare pnpm@latest --activate && npm install -g wrangler
      - run:
          name: Build Astro
          command: pnpm --filter astro run build
      - run:
          name: Deploy blog
          command: wrangler pages deploy astro/dist/blog.bokken.io --project-name=bokken-blog --branch=main
      - run:
          name: Deploy www
          command: wrangler pages deploy astro/public-www --project-name=bokken-www --branch=main
      - run:
          name: Deploy x
          command: wrangler pages deploy astro/public-x --project-name=bokken-x --branch=main

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-cloudflare
        filters:
          branches:
            only: main
