version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: ssh bokken@ssh.bokken.io -o "StrictHostKeyChecking no" "cd bokken.io && git pull -f && ./scripts/build && docker-compose up -f docker-compose.yml -f wiki/docker-compose.yml -d"

workflows:
  version: 2
  deploy:
    jobs:
      - publish:
          filters:
            branches:
              only: main
