version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run:
          command: ssh bokken@bokken.io -o "StrictHostKeyChecking no" "git clone https://github.com/negibokken/bokken.io.git for_build && cd for_build && ./scripts/build && cd ../bokken.io && docker-compose up -d bokken.io && cd .. && rm -rf for_build"

workflows:
  version: 2
  deploy:
    jobs:
      - publish:
          filters:
            branches:
              only: master
