version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: ssh bokken@bokken.io \
              "rm bokken.io
               git clone https://github.com/negibokken/bokken.io.git; \
               cd bokken.io
               ./scripts/update
              "

workflows:
  version: 2
  deploy:
    jobs:
      - publish:
          filters:
            branches:
              only: master
