version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: ls
      - run: scp index.html bokken@bokken.io:~/

workflows:
  version: 2
  deploy:
    jobs:
      - publish:
          filters:
            branches:
              only: master
