services:
  https-portal:
    image: steveltn/https-portal:1.12
    ports:
      - "80:80"
      - "443:443"
    links:
      - "bokken.io"
    restart: always
    depends_on:
      - bokken.io
    environment:
      DOMAINS: "bokken.io -> http://bokken.io:8080, www.bokken.io -> http://bokken.io:8080, blog.bokken.io -> http://bokken.io:8080, x.bokken.io -> http://bokken.io:8080"
      STAGE: production
      ERROR_LOG: default
      ACCESS_LOG: default
    volumes:
      - /var/log/nginx:/var/log/nginx

  bokken.io:
    image: bokken.io
    volumes:
      - /var/log/nginx:/var/log/nginx
