#!/bin/bash

DOMAIN='https://blog.bokken.io'

node scripts/site-gen.js
if [ "$?" == 0 ]; then
  echo -e "\033[32m✓ \033[m sites" > /dev/stderr
else
  echo -e "\033[31m✗ \033[m sites" > /dev/stderr
fi

function findIndex() {
  target=$1;
  shift
  arr=($@);
  for i in `seq 0 $(expr ${#arr[@]} - 1)`; do
    if [ "$target" = "${arr[i]}" ]; then
      return $i;
    fi
  done
  return -1;
}

base="articles"
directories=($(ls $base | grep -e "\d*-\d*-\d*"))
for i in `seq 0 $(expr ${#directories[@]} - 1)`; do
  dir=${directories[i]}
  path=`find $base/$dir -name "*.md"`
  # Skip if empty directory
  if [ "$path" = "" ]; then
    continue
  fi
  filename=`basename $path`
  name=`echo $filename | sed 's/\.[^.]*$//'`

  outpath=$base/$dir/$name.html

  findIndex $dir ${directories[@]}
  idx=$?

  prevPath=""
  nextPath=""
  if ! [ "$idx" = "0" ]; then
    prev=`expr $idx - 1`
    prevPath=`find $base/"${directories[prev]}" -name "*.md" | sed -e 's/\.[^.]*$/.html/'`
  fi
  if ! [ "$idx" = "$(expr ${#directories[@]} - 1)" ]; then
    next=`expr $idx + 1`
    nextPath=`find $base/"${directories[next]}" -name "*.md" | sed -e 's/\.[^.]*$/.html/'`
  fi

  node scripts/blog-gen.js $path ../templates/blog-article.ejs "$prevPath" "$nextPath" > $outpath

  if [ "$?" == 0 ]; then
    echo -e "\033[32m✓ \033[m $outpath" > /dev/stderr
  else
    echo -e "\033[31m✗ \033[m $outpath" > /dev/stderr
  fi
done

node scripts/blog-index-gen.js > index.html
if [ "$?" == 0 ]; then
  echo -e "\033[32m✓ \033[m index.html" > /dev/stderr
else
  echo -e "\033[31m✗ \033[m index.html" > /dev/stderr
fi
node scripts/sitemap-gen.js > sitemap.xml
if [ "$?" == 0 ]; then
  echo -e "\033[32m✓ \033[m sitemap.xml" > /dev/stderr
else
  echo -e "\033[31m✗ \033[m sitemap.xml" > /dev/stderr
fi
node scripts/atom-gen.js
if [ "$?" == 0 ]; then
  echo -e "\033[32m✓ \033[m atom.xml" > /dev/stderr
else
  echo -e "\033[31m✗ \033[m atom.xml" > /dev/stderr
fi
